includes:
    #TODO: Rename this file. These functions are what enables single use nodes in nodepool.
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: "Build failed.  To recheck use 'xenserver: recheck'.  For 3rd party ci contact info: https://wiki.openstack.org/wiki/ThirdPartySystems"
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        # TODO: Change "myvendor" below to your vendor's name to add a custom
        # recheck trigger that runs the check pipeline jobs when someone
        # adds a comment to a review that says "recheck myvendor".
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*xenserver:*\s*recheck\s*$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    merge-failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Upstream change {change} has a merge failure


  - name: silent
    description: Newly uploaded patchsets enter this pipeline to check jobs whose results are NOT to be posted (because e.g. they are not yet stable)
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*xenserver:*\s*recheck\s*$
    success:
      smtp:
        to: jianghua.wang@citrix.com
        from: zuul@zuul.openstack.xenproject.org
        subject: 'Silent check of {change.project} {change.number},{change.patchset} passed'
    failure:
      smtp:
        to: jianghua.wang@citrix.com
        from: zuul@zuul.openstack.xenproject.org
        subject: 'Silent check of {change.project} {change.number},{change.patchset} failed'


jobs:
  - name: ^dsvm-tempest.*$
    skip-if:
    - project: ^openstack/nova$
      branch: ^master$
      all-files-match-any:
        - ^.*\.rst$
        - ^doc/.*$
        - ^nova/tests/.*$
        - ^nova/virt/baremetal/.*$
        - ^nova/virt/hyperv/.*$
        - ^nova/virt/ironic/.*$
        - ^nova/virt/vmwareapi/.*$
        - ^nova/virt/xenapi/.*$
        - ^tools/.*$
        - ^tox.ini$
    parameter-function: single_use_node
    branch: ^master.*$
    #swift:
    #  - name: logs


projects:
  - name: openstack/fuel-plugin-xenserver
    check:
      - check-fuel-xenserver-plugin

  - name: openstack-dev/sandbox
    check:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network

  - name: openstack/nova
    silent:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network

  - name: openstack/neutron
    silent:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network

  - name: openstack/tempest
    silent:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network

  - name: openstack-dev/devstack
    silent:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network

  - name: openstack/xenapi-os-testing
    silent:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network
